version: "3"
services:
  proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
# uso de la red en el servicio      
    networks: 
      - sitenet
# definición de red
networks:
  sitenet:
    driver: bridge